-- brand カラム追加
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand TEXT;
CREATE INDEX IF NOT EXISTS idx_products_brand ON products(brand);

-- 既存10商品を一括 UPDATE（products.id は保持 → search_history の FK が壊れない）
UPDATE products SET sku='SKU-001', name='innovator スーツケース エキスパンダブル 38+5L',   brand='innovator', jan=NULL, model='INV43EX',    category='スーツケース',     my_price=24800, cost_price=13200, stock=15, is_monitored=TRUE, sales_rank=1,  last_suggestion_level='urgent',    last_checked_at=now() WHERE sku='SHOE-001';
UPDATE products SET sku='SKU-002', name='innovator スーツケース 75L Mサイズ CARRY WAGON',   brand='innovator', jan=NULL, model='IW66',       category='スーツケース',     my_price=18800, cost_price=10500, stock=22, is_monitored=TRUE, sales_rank=2,  last_suggestion_level='recommend', last_checked_at=now() WHERE sku='SHOE-002';
UPDATE products SET sku='SKU-003', name='Salomon AERO GLIDE 4 GRVL ランニングシューズ',      brand='Salomon',   jan=NULL, model='L49174',     category='シューズ',         my_price=19800, cost_price=11200, stock=18, is_monitored=TRUE, sales_rank=3,  last_suggestion_level='recommend', last_checked_at=now() WHERE sku='SHOE-003';
UPDATE products SET sku='SKU-004', name='Salomon XA PRO 3D V9 GTX トレイルランニング',       brand='Salomon',   jan=NULL, model='L47987',     category='シューズ',         my_price=24500, cost_price=13200, stock=12, is_monitored=TRUE, sales_rank=4,  last_suggestion_level='urgent',    last_checked_at=now() WHERE sku='SHOE-004';
UPDATE products SET sku='SKU-005', name='Columbia スパイアーバレー ウィンドブレーカー ブラック', brand='Columbia',  jan=NULL, model='WR7658',     category='アウトドアウェア', my_price=10200, cost_price=5400,  stock=45, is_monitored=TRUE, sales_rank=5,  last_suggestion_level='monitor',   last_checked_at=now() WHERE sku='SHOE-005';
UPDATE products SET sku='SKU-006', name='Columbia Spire Valley ジャケット ネイビー',          brand='Columbia',  jan=NULL, model='WR7658',     category='アウトドアウェア', my_price=9700,  cost_price=5400,  stock=28, is_monitored=TRUE, sales_rank=6,  last_suggestion_level='good',      last_checked_at=now() WHERE sku='SHOE-006';
UPDATE products SET sku='SKU-007', name='AVIREX 4WAY ボンサック ボストン/ショルダー/バックパック', brand='AVIREX',    jan=NULL, model='AVX3514',    category='バッグ',           my_price=9000,  cost_price=5100,  stock=38, is_monitored=TRUE, sales_rank=7,  last_suggestion_level='good',      last_checked_at=now() WHERE sku='SHOE-007';
UPDATE products SET sku='SKU-008', name='CHUMS トートバッグ ブービーステッチ',                 brand='CHUMS',     jan=NULL, model='CH60-4039',  category='バッグ',           my_price=8900,  cost_price=4400,  stock=54, is_monitored=TRUE, sales_rank=8,  last_suggestion_level='urgent',    last_checked_at=now() WHERE sku='SHOE-008';
UPDATE products SET sku='SKU-009', name='Columbia Urban Hike Graphic Tシャツ',                 brand='Columbia',  jan=NULL, model='PG3033',     category='アパレル',         my_price=4680,  cost_price=2400,  stock=89, is_monitored=TRUE, sales_rank=9,  last_suggestion_level='recommend', last_checked_at=now() WHERE sku='SHOE-009';
UPDATE products SET sku='SKU-010', name='Columbia SKYRIDE STREET WATERPROOF スニーカー',       brand='Columbia',  jan=NULL, model='YU8523',     category='シューズ',         my_price=13100, cost_price=7000,  stock=25, is_monitored=TRUE, sales_rank=10, last_suggestion_level='recommend', last_checked_at=now() WHERE sku='SHOE-010';
